export const GET_PATHS = 'GET_PATHS'
export const CLEAR_PATHS = 'CLEAR_PATHS'

export const GET_NOBLE_PATH_WAKE = 'GET_NOBLE_PATH_WAKE'
export const GET_NOBLE_PATH_GYM = 'GET_NOBLE_PATH_GYM'
export const GET_NOBLE_PATH_FOOD = 'GET_NOBLE_PATH_FOOD'
export const GET_NOBLE_PATH_JOURNAL = 'GET_NOBLE_PATH_JOURNAL'

export const ADD_PATH = 'ADD_PATH'
export const ADD_NOBLEPATH_WAKE = 'ADD_NOBLEPATH_WAKE'
export const ADD_NOBLEPATH_GYM = 'ADD_NOBLEPATH_GYM'
export const ADD_NOBLEPATH_FOOD = 'ADD_NOBLEPATH_FOOD'
export const ADD_NOBLEPATH_JOURNAL = 'ADD_NOBLEPATH_JOURNAL'

export const DELETE_PATH = 'DELETE_PATH'

export const PATH_ERROR = 'PATH_ERROR'
export const UPDATE_PATH = 'UPDATE_PATH'

export const UPDATE_NOBLE_PATH_WAKE = 'UPDATE_NOBLE_PATH_WAKE'
export const UPDATE_NOBLE_PATH_FOOD = 'UPDATE_NOBLE_PATH_FOOD'
export const UPDATE_NOBLE_PATH_GYM = 'UPDATE_NOBLE_PATH_GYM'
export const UPDATE_NOBLE_PATH_JOURNAL = 'UPDATE_NOBLE_PATH_JOURNAL'

export const DELETE_NOBLE_PATH_WAKE = 'DELETE_NOBLE_PATH_WAKE'
export const DELETE_NOBLE_PATH_FOOD = 'DELETE_NOBLE_PATH_FOOD'
export const DELETE_NOBLE_PATH_GYM = 'DELETE_NOBLE_PATH_GYM'
export const DELETE_NOBLE_PATH_JOURNAL = 'DELETE_NOBLE_PATH_JOURNAL'

export const SET_CURRENT = 'SET_CURRENT'
export const CLEAR_CURRENT = 'CLEAR_CURRENT'

export const FILTER_PATHS = 'FILTER_PATHS'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const HIDE_PATHS = 'HIDE_PATHS'
// alerts may also be useful to alert players to events ingame such as out of bounds etc
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const RONIN_LOADED = 'RONIN_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
